title: Congcong Li's Homepage
description: > # this means to ignore newlines until "show_excerpts:"
  Stay Hungry. Stay Foolish.

google_analytics: G-RBNH9Q5CVW
remote_theme: jekyll/minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
